name: Mirror to GitLab at Garena

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: 'https://gitlab.gamertocoder.garena.co.th/2022/gamertocoder-628'
        env:
          FORCE_PUSH: 'true'
          GITLAB_HOSTNAME: 'gitlab.gamertocoder.garena.co.th'
          GITLAB_USERNAME: '2022'
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: '1008'
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
